### PR TITLE
Issue: Ambigious match when multiple events handled by single handler …

### LINKED ISSUE #1: Ambigious match when multiple events handled by single handler class
When implementing multiple handler interfaces in single class, "Ambigious match found"
exception is thrown if content moving/moved event was one of impemented interfaces.

### PR DESCRIPTION
**Pull request by AgnieszkaJania**
…class #1, GetMethod overload used with specified parameters of the method to get

### CODE REVIEW

File: src/EpiEasyEvents/EventsRegistry.cs [hunk 1]
```diff
@@ -230,7 +230,7 @@ private void HandleEvent<TEventArgs>(Type handlerInterface, TEventArgs eventArgs
             foreach (var handler in eventHandlers)
             {
                 var handleMethod = handler.GetType()
-                    .GetMethod(nameof(IContentEventHandler<PageData, ContentEventArgs>.Handle));
+                    .GetMethod(nameof(IContentEventHandler<PageData, ContentEventArgs>.Handle), new Type[]{eventArgs.Content.GetType(), eventArgs.GetType()});
```
Comment (tomaszmadeyski) [inline src/EpiEasyEvents/EventsRegistry.cs]: you can make use of new syntax and omit the type. Also, a type of content is already checked a bit above with additional null check, which is lacking in your version. So, these two changes together can make line 233 look like:

`.GetMethod(nameof(IContentEventHandler<PageData, ContentEventArgs>.Handle), new []{ pageType, eventArgs.GetType()});`
